[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture amd64",
    "apt-get update",
    "apt-get install --assume-yes libusb-1.0-0-dev:amd64 libftdi1-dev:amd64 libudev-dev:amd64 libssl-dev:amd64",
]
[target.aarch64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install --assume-yes libusb-1.0-0-dev:arm64 libftdi1-dev:arm64 libudev-dev:arm64 libssl-dev:arm64",
]

